### PR TITLE
Respect the terms of the GNU General Public License

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review and confirm that you agree with the change of license for the files that you authored, thanks!

### CODE REVIEW

**Comment by MartyLake** [comment]
LGTM. I agree with the change of license for the files I authored !

**Comment by MartyLake** [comment]
Do we have to copyright every source file ? Or just the repository ?

**Comment by MartyLake** [comment]
I think we have to keep it this way: https://www.gnu.org/licenses/gpl-faq.html#GPLOmitPreamble

**Comment by McMartin** [comment]
According to https://github.com/McMartin/JUCE.cmake/blob/97ce486c4159c283c223b13f15c854d374b5797f/LICENSE#L629, it is safer to do so.

**Pull request merged**
