### PR TITLE
Add simple GUI application examples

### PR DESCRIPTION
**Pull request by McMartin**
Add `CMakeLists.txt` files for JUCE's examples that are simple GUI applications, i.e. they don't define any `JUCE_` option and don't use resources.

@MartyLake: please have a look, thanks!

### CODE REVIEW

**Comment by MartyLake** [comment]
As you already know `JUCE.cmake/examples/build/OSCMonitor/JuceLibraryCode/juce_osc.mm:2:10: fatal error: 'juce_osc/juce_osc.mm' file not found`

**Comment by McMartin** [comment]
I have pushed a new version of the branch, rebased on top of `master`.

**Comment by McMartin** [comment]
@MartyLake: I pushed a last commit at then end of the branch, in order to keep the CI turn around time manageable. Please review that one too, thanks!

**Comment by MartyLake** [comment]
Building and running on SX10.9.

A warning concerning QuickTime framework shows on these examples: AnimationAppExample, BouncingBallWavetableDemo, AudioAppExample, OSCMonitor, MPETest, OSCSender, OSCReceiver.

`ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks//QuickTime.framework/QuickTime, file was built for i386 which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks//QuickTime.framework/QuickTime`

Read the diff, everything looks fine to me !

**Comment by McMartin** [comment]
@MartyLake: I also saw the warning concerning QuickTime on [Travis ](https://travis-ci.org/McMartin/JUCE.cmake/builds/134550950#L93). Could you check whether you get the same warning when building these examples with the `Introjucer`/`Projucer`? Thanks!

**Comment by MartyLake** [comment]
Same warning ⚠ with Projucer also! 

Le 3 juin 2016 17:08:58 GMT+02:00, Alain Martin <notifications@github.com> a écrit :
>@MartyLake: I also saw the warning concerning QuickTime on [Travis
>](https://travis-ci.org/McMartin/JUCE.cmake/builds/134550950#L93).
>Could you check whether you get the same warning when building these
>examples with the `Introjucer`/`Projucer`? Thanks!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/McMartin/JUCE.cmake/pull/2#issuecomment-223605436

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by McMartin** [comment]
@MartyLake: Thanks for checking. Let's merge then!

**Comment by MartyLake** [comment]
Gg wp! 👍

Le 4 juin 2016 11:17:39 GMT+02:00, Alain Martin <notifications@github.com> a écrit :
>Merged #2.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/McMartin/JUCE.cmake/pull/2#event-681888604

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Pull request merged**
