### PR TITLE
Handle preprocessor definitions written one per line

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by MartyLake** [comment]
LGTM. 

however, wouldn't it be easier to std:replace instead of join + split?

**Comment by McMartin** [comment]
@MartyLake: Good point. Also we are not escaping existing `;`. I guess I should write something less generic, and more geared towards writing CMake code.

**Comment by MartyLake** [comment]
@McMartin

Maybe the join  function can take a list of characters to escape as another
 parameter, and Espace any character that exists in any of the strings
passed in?

**Comment by McMartin** [comment]
@MartyLake: I added two `escape` functions (one for `std::string` and one for `std::vector<std::string>`) so we can combine calls to `split`, `escape` and `join`. Please have another look!

**Comment by MartyLake** [comment]
Besides the minor correction, looks good to me!

**Comment by MartyLake** [comment]
Good job !!! :)

**Comment by McMartin** [comment]
@MartyLake: this PR doesn't work... 😞 
When calling
```
jucer_project_begin(
  PROJECT_NAME "Foo"
  PROJECT_TYPE "GUI Application"
  PREPROCESSOR_DEFINITIONS "A=1;B=2"
)
```
we get the error message: `Unsupported project setting: B=2`.
I need to figure out another solution...

**Comment by McMartin** [comment]
Fixed by https://github.com/McMartin/JUCE.cmake/pull/103

**Pull request merged**
