### PR TITLE
Copy a PkgInfo file in the plug-in bundles

### LINKED ISSUE #218: PkgInfo file for vst bundles.
Hi @McMartin !
It seems that the projucer is generating a pkginfo file automatically for VST and AU bundles.
According to this link: https://ccrma.stanford.edu/~kapilkm/220c/Vst_XCode.html:
```Create a blank text file in the ‘Resources’ section, put BNDL???? in it, and save it as PkgInfo. This is to make sure the OS X Finder sees the plugin as an actual executable, and not just another folder of stuff (which is what a bundle is, really).```
It would be a good thing if JUCE.cmake could setup the xcode project to generate this file in the VST and AU bundles automatically.

### PR DESCRIPTION
**Pull request by McMartin**
Resolves #218 

@MartyLake: please review, thanks!
@WGuLL: please check that it works for you.

### CODE REVIEW

**Comment by WGuLL** [comment]
@McMartin It works! Thanks! 👍

**Comment by MartyLake** [comment]
LGTM (I suppose the multiple lines for crafting the command are mandatory?)

**Comment by McMartin** [comment]
@MartyLake: yes they are, I had to do something similar in https://github.com/McMartin/JUCE.cmake/pull/217 (https://github.com/McMartin/JUCE.cmake/pull/217/commits/792b34711ac4065a7ab4ea4522f21a435e54669d#diff-d7ac1cfde9bf2d7ef9cccf6fab14bc6eR1676)

**Comment by McMartin** [comment]
@MartyLake: actually I was wrong, the multiple lines for crafting the command are not necessary. See #223  for the fix.

**Pull request merged**
