### PR TITLE
Do not use Reprojucer.cmake to configure its helper executables

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake: The diff is not really readable, so it might be easier to have a look at the final state directly:
- https://github.com/McMartin/JUCE.cmake/blob/a54ebbeb91bd1dca279538f8886a2b0ec5ea77d1/cmake/BinaryDataBuilder/CMakeLists.txt
- https://github.com/McMartin/JUCE.cmake/blob/a54ebbeb91bd1dca279538f8886a2b0ec5ea77d1/cmake/IconBuilder/CMakeLists.txt

**Comment by MartyLake** [comment]
Since one JUCE_modules_DIR must contain **all** juce folders ( https://github.com/McMartin/JUCE.cmake/blob/a54ebbeb91bd1dca279538f8886a2b0ec5ea77d1/cmake/BinaryDataBuilder/CMakeLists.txt#L26 ), it doesn't make sense to allow the user to provide a list, does it ?

**Comment by McMartin** [comment]
The main (and maybe only) user is `Reprojucer.cmake` and being able to provide a list makes its code simpler (see https://github.com/McMartin/JUCE.cmake/blob/master/cmake/Reprojucer.cmake#L1434). Anyway, this is the only thing that didn't change in that PR (and I don't intend to change it now). :smile:

**Comment by MartyLake** [comment]
LGTM then ;)

**Pull request merged**
