### PR TITLE
Support C++ standard settings

### LINKED ISSUE #131: The "C++ Language Standard" build configuration setting is not supported

### LINKED ISSUE #164: The "C++ standard to use" exporter setting is not supported

### PR DESCRIPTION
**Pull request by McMartin**
Resolves #131 
Resolves #164 

@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by MartyLake** [comment]
So for now, the choice between gnu or clang flavor is not supported? 

LGTM

**Comment by McMartin** [comment]
@MartyLake: good point, I'll fix that.

**Comment by McMartin** [comment]
@MartyLake: I reworked the branch to address your comment, please have another look, thanks!

**Comment by MartyLake** [comment]
LGTM :-D

**Pull request merged**
